version: '3.7'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    network_mode: "host"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: pass
      MINIO_API_REQUESTS_MAX: 100G # max upload in minio
    command: server --console-address ":9005" /data
#    ports:
#      - 9000:9000
#      - 9001:9005
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
